# Generated by Django 5.2.8 on 2025-12-16 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_order_awb_code_order_courier_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pickup_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
