# Generated by Django 5.2.8 on 2025-12-16 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_order_pickup_data_order_pickup_scheduled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=100)),
                ('weight_value', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('weight_unit', models.CharField(choices=[('kg', 'kg'), ('g', 'g')], default='kg', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
