# Generated by Django 5.2.8 on 2025-12-16 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='weight_unit',
            field=models.CharField(choices=[('kg', 'kg'), ('g', 'g'), ('L', 'L')], default='kg', max_length=10),
        ),
    ]
